### ISSUE TITLE
Legion Sniper Rifle and Mags are missing sprites

### ISSUE THREAD

**Issue by CaputCapital** [f13babylon/f13babylon#121]
---- Reproduction: ----

Sprites are missing for the Legion explorer sniper rifle and the 10 round magazines that come with it.
Example: Legion Explorer Sniper loadout appears to have correct sprites in the preview but the item sprites are invisible.

---- Screenshot: ----

![explorersniperriflemissingsprite](https://github.com/f13babylon/f13babylon/assets/60798623/735e50e5-990a-4350-ba8d-0e0fa9250ee1)

**Comment by iMoeMoe** [comment]
looked into the code, the Explorer's Rifle is nowhere to be found, correct me if am wrong 

Ammo Box:

https://github.com/f13babylon/f13babylon/blob/main/code/modules/projectiles/boxes_magazines/external/sniper.dm

https://github.com/f13babylon/f13babylon/blob/main/code/modules/projectiles/boxes_magazines/external/rifle.dm

Gun, Ballistic:

https://github.com/f13babylon/f13babylon/blob/main/code/modules/projectiles/guns/ballistic/rifle.dm

**Comment by iMoeMoe** [comment]
nevermind, found it in lmg.dm, some retard put the sniper mag in lmg.dm instead of sniper.dm
