### ISSUE TITLE
The "Verminkiller" / Upgraded Varmint Rifle has no sprite

### ISSUE THREAD

**Issue by SpookyJumpscare** [f13babylon/f13babylon#399]
---- Testmerges: ----
Round ID: 220
BYOND Version: 514.1589
Server revision compiled on: 2023-12-20T22:12:46+00:00
Master commit: [47bb8b73497be419250f6b126342df67bdb4b696](https://github.com/f13babylon/f13babylon/commit/47bb8b73497be419250f6b126342df67bdb4b696)
The following pull requests are currently test merged:
[#335: 'OVERHAUL PT. 5: SMGS REMADE' by mazzinsanity at commit 376a7adcc0](https://github.com/f13babylon/f13babylon/pull/335)
[#348: 'Adds the ability to construct (non-radioactive) water turfs, adjusts crafting code to allow the crafting of turfs.' by BadIsMyUsername at commit e7222675f0](https://github.com/f13babylon/f13babylon/pull/348)
[#363: 'Defensive Structure Balance Tweaks' by mazzinsanity at commit 67172564dc](https://github.com/f13babylon/f13babylon/pull/363)
[#374: 'Crafting Recipe Adjustments, Explosive Skill Given to More Roles, & Fixes for Scribes' by Stutternov at commit 39e05c56b0](https://github.com/f13babylon/f13babylon/pull/374)
[#377: 'Ports Railings From TG' by GreytidePanda at commit dec3c7dc8f](https://github.com/f13babylon/f13babylon/pull/377)
[#381: 'Shield Change (As Requested)' by Stutternov at commit 29d7a46504](https://github.com/f13babylon/f13babylon/pull/381)

Local commit: ac981ffa5833f08b260149f0b6fb72b97dffdcf5
TGS version: 5.18.2
DMAPI version: 5.6.2

Current Informational Settings:
Protect Authority Roles From Traitor: 0
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1

---- Reproduction: ----
This one is thankfully simple and shouldn't be a hard issue to reproduce, just craft or spawn in a verminkiller / upgraded varmint rifle and you will be able to easily see that it doesn't have a sprite for the gun. It will show up when held but there isn't an icon/sprite for it in your inventory or on the ground. 

---- Screenshots: ----
Seeing as this issue is about a missing sprite/icon adding screenshots won't help because there will not be an issue to see.

---- Additional context: ----
I A-helped the issue and confirmed with one of the admins that they also could not see the sprite at all and that issue was not happening to only me.

**Comment by ThyBaron** [comment]
This is fixed! @maaacha
